#!/usr/bin/env bash
#
# ACCEPTANCE M0 — hook-propagation spike sentinel.
#
# Runs the spike fork test, reads its on-chain result artifact, records the
# Model B/A decision + evidence into docs/ARCHITECTURE.md, and prints the
# sentinel. Both B and A are valid passes — the goal is a definitive recorded
# answer, not B specifically.
#
# IMMUTABLE (docs/ACCEPTANCE.md #3): never edit this script to force a pass.
set -euo pipefail
cd "$(dirname "$0")/.."

fail() { echo "ACCEPTANCE M0 FAIL: $1"; exit 1; }

# --- prerequisites (surface blockers; never fabricate a result) ----------
if [ -f .env ]; then set -a; . ./.env; set +a; fi
[ -n "${BASE_RPC_URL:-}" ] || fail "BASE_RPC_URL not set in .env — a Base RPC is required to fork."
command -v anvil >/dev/null 2>&1 || fail "anvil not found on PATH — install Foundry (foundryup)."
[ -x node_modules/.bin/vitest ] || fail "vitest not installed — run the install step (pnpm install) first."

# --- run the spike --------------------------------------------------------
echo "Running M0 hook-propagation spike (Base fork)..."
node_modules/.bin/vitest run test/fork --reporter=dot || fail "spike test failed — see output above."

ARTIFACT="artifacts/spike-result.json"
[ -f "$ARTIFACT" ] || fail "spike did not produce $ARTIFACT."

# --- extract + validate the verdict --------------------------------------
RESULT="$(node -e 'const r=require("./artifacts/spike-result.json"); if(!["A","B"].includes(r.result)) process.exit(3); process.stdout.write(r.result)')" \
  || fail "no definitive SPIKE_RESULT (A|B) in $ARTIFACT."

# --- record decision + evidence into docs/ARCHITECTURE.md (idempotent) ----
node - "$RESULT" <<'NODE'
const fs = require("fs");
const result = process.argv[2];
const r = require("./artifacts/spike-result.json");
const doc = "docs/ARCHITECTURE.md";

const model = result === "B"
  ? "**Model B** selected: per-part pre-hook withdrawal (capital stays in Aave until each part settles)."
  : "**Model A** selected: agent withdraws the next tranche per re-up.";
const propagation = r.equalAcrossParts
  ? `both parts carried the identical appData \`${r.appDataHex}\` (distinct validTo: ${r.order0ValidTo} vs ${r.order1ValidTo})`
  : `the parts did NOT carry a common appData (order0 \`${r.order0AppData}\`, order1 \`${r.order1AppData}\`)`;

const block = [
  "<!-- BEGIN M0 SPIKE RESULT (generated by scripts/verify-m0.sh) -->",
  "## Step 0 — Spike outcome (RESOLVED)",
  "",
  `**SPIKE_RESULT=${result}** — ${model}`,
  "",
  `Evidence (local Base mainnet fork @ block ${r.forkBlockNumber}):`,
  `- The TWAP handler's \`getTradeableOrder\` derived the discrete order for part 0 and part 1; ${propagation}.`,
  `- Hook-fire count = ${r.firedCount}/2: impersonating GPv2Settlement, \`HooksTrampoline.execute([preHook])\` ran the observable Counter pre-hook once per propagated part.`,
  "- Scope: this proves the MECHANICAL half (appData propagates to every part, and the trampoline executes the committed hook). CoW hooks are an off-chain solver convention, NOT enforced on-chain — live-solver behavior is confirmed at M6, not here.",
  "",
  "_Generated by `pnpm verify:m0`. Re-running regenerates this block._",
  "<!-- END M0 SPIKE RESULT -->",
].join("\n");

let md = fs.readFileSync(doc, "utf8");
const begin = "<!-- BEGIN M0 SPIKE RESULT (generated by scripts/verify-m0.sh) -->";
const end = "<!-- END M0 SPIKE RESULT -->";
const re = new RegExp(`${begin.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${end}`, "m");
if (re.test(md)) {
  md = md.replace(re, block);
} else {
  md = md.replace(/\s*$/, "\n") + "\n" + block + "\n";
}
fs.writeFileSync(doc, md);
console.log(`Recorded SPIKE_RESULT=${result} in ${doc}.`);
NODE

# --- sentinel -------------------------------------------------------------
echo "SPIKE_RESULT=${RESULT}"
echo "ACCEPTANCE M0 PASS"
